//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaDoZe_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademiaDoZe_WPF.Properties.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Administrador.
        /// </summary>
        public static string txtAdministrador {
            get {
                return ResourceManager.GetString("txtAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Admissão.
        /// </summary>
        public static string txtAdmissao {
            get {
                return ResourceManager.GetString("txtAdmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alergias.
        /// </summary>
        public static string txtAlergias {
            get {
                return ResourceManager.GetString("txtAlergias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altura.
        /// </summary>
        public static string txtAltura {
            get {
                return ResourceManager.GetString("txtAltura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aluno.
        /// </summary>
        public static string txtAluno {
            get {
                return ResourceManager.GetString("txtAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Antebraço Direito.
        /// </summary>
        public static string txtAntDir {
            get {
                return ResourceManager.GetString("txtAntDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Antebraço Esquerdo.
        /// </summary>
        public static string txtAntEsq {
            get {
                return ResourceManager.GetString("txtAntEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anual.
        /// </summary>
        public static string txtAnual {
            get {
                return ResourceManager.GetString("txtAnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atendente.
        /// </summary>
        public static string txtAtendente {
            get {
                return ResourceManager.GetString("txtAtendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aulas.
        /// </summary>
        public static string txtAulas {
            get {
                return ResourceManager.GetString("txtAulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Avaliação.
        /// </summary>
        public static string txtAvaliacao {
            get {
                return ResourceManager.GetString("txtAvaliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro.
        /// </summary>
        public static string txtBairro {
            get {
                return ResourceManager.GetString("txtBairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bíceps Direito.
        /// </summary>
        public static string txtBicDir {
            get {
                return ResourceManager.GetString("txtBicDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bíceps Esquerdo.
        /// </summary>
        public static string txtBicEsq {
            get {
                return ResourceManager.GetString("txtBicEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP.
        /// </summary>
        public static string txtCep {
            get {
                return ResourceManager.GetString("txtCep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade.
        /// </summary>
        public static string txtCidade {
            get {
                return ResourceManager.GetString("txtCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cintura.
        /// </summary>
        public static string txtCintura {
            get {
                return ResourceManager.GetString("txtCintura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CLT.
        /// </summary>
        public static string txtClt {
            get {
                return ResourceManager.GetString("txtClt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Colaborador.
        /// </summary>
        public static string txtColaborador {
            get {
                return ResourceManager.GetString("txtColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento.
        /// </summary>
        public static string txtComplemento {
            get {
                return ResourceManager.GetString("txtComplemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        public static string txtConfig {
            get {
                return ResourceManager.GetString("txtConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Coxa Direita.
        /// </summary>
        public static string txtCoxaDir {
            get {
                return ResourceManager.GetString("txtCoxaDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Coxa Esquerda.
        /// </summary>
        public static string txtCoxaEsq {
            get {
                return ResourceManager.GetString("txtCoxaEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        public static string txtCpf {
            get {
                return ResourceManager.GetString("txtCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data.
        /// </summary>
        public static string txtData {
            get {
                return ResourceManager.GetString("txtData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diabete.
        /// </summary>
        public static string txtDiabete {
            get {
                return ResourceManager.GetString("txtDiabete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        public static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrada.
        /// </summary>
        public static string txtEntrada {
            get {
                return ResourceManager.GetString("txtEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estagio.
        /// </summary>
        public static string txtEstagio {
            get {
                return ResourceManager.GetString("txtEstagio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fim.
        /// </summary>
        public static string txtFim {
            get {
                return ResourceManager.GetString("txtFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Frequência.
        /// </summary>
        public static string txtFrequencia {
            get {
                return ResourceManager.GetString("txtFrequencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gravidez.
        /// </summary>
        public static string txtGravidez {
            get {
                return ResourceManager.GetString("txtGravidez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        public static string txtId {
            get {
                return ResourceManager.GetString("txtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID Aluno.
        /// </summary>
        public static string txtIdAluno {
            get {
                return ResourceManager.GetString("txtIdAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID Endereço.
        /// </summary>
        public static string txtIdEnd {
            get {
                return ResourceManager.GetString("txtIdEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma.
        /// </summary>
        public static string txtIdioma {
            get {
                return ResourceManager.GetString("txtIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IMC.
        /// </summary>
        public static string txtImc {
            get {
                return ResourceManager.GetString("txtImc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Início.
        /// </summary>
        public static string txtInicio {
            get {
                return ResourceManager.GetString("txtInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instrutor.
        /// </summary>
        public static string txtInstrutor {
            get {
                return ResourceManager.GetString("txtInstrutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Labirinto.
        /// </summary>
        public static string txtLabirinto {
            get {
                return ResourceManager.GetString("txtLabirinto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lesões Musculares.
        /// </summary>
        public static string txtLesoesMusculares {
            get {
                return ResourceManager.GetString("txtLesoesMusculares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logout.
        /// </summary>
        public static string txtLogout {
            get {
                return ResourceManager.GetString("txtLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro.
        /// </summary>
        public static string txtLogradouro {
            get {
                return ResourceManager.GetString("txtLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro.
        /// </summary>
        public static string txtLogradouroh1 {
            get {
                return ResourceManager.GetString("txtLogradouroh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Massa Gorda.
        /// </summary>
        public static string txtMassaGor {
            get {
                return ResourceManager.GetString("txtMassaGor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Massa Magra.
        /// </summary>
        public static string txtMassaMag {
            get {
                return ResourceManager.GetString("txtMassaMag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matrícula.
        /// </summary>
        public static string txtMatricula {
            get {
                return ResourceManager.GetString("txtMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mensal.
        /// </summary>
        public static string txtMensal {
            get {
                return ResourceManager.GetString("txtMensal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de nascimento.
        /// </summary>
        public static string txtNascimento {
            get {
                return ResourceManager.GetString("txtNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma.
        /// </summary>
        public static string txtNenhuma {
            get {
                return ResourceManager.GetString("txtNenhuma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string txtNome {
            get {
                return ResourceManager.GetString("txtNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número.
        /// </summary>
        public static string txtNumero {
            get {
                return ResourceManager.GetString("txtNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Objetivo.
        /// </summary>
        public static string txtObjetivo {
            get {
                return ResourceManager.GetString("txtObjetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observação.
        /// </summary>
        public static string txtObservacao {
            get {
                return ResourceManager.GetString("txtObservacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Outras.
        /// </summary>
        public static string txtOutras {
            get {
                return ResourceManager.GetString("txtOutras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a País.
        /// </summary>
        public static string txtPais {
            get {
                return ResourceManager.GetString("txtPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Panturrilha Direita.
        /// </summary>
        public static string txtPantDir {
            get {
                return ResourceManager.GetString("txtPantDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Panturrilha Esquerda.
        /// </summary>
        public static string txtPantEsq {
            get {
                return ResourceManager.GetString("txtPantEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Percentual de Gordura.
        /// </summary>
        public static string txtPercGor {
            get {
                return ResourceManager.GetString("txtPercGor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso.
        /// </summary>
        public static string txtPeso {
            get {
                return ResourceManager.GetString("txtPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso Ideal.
        /// </summary>
        public static string txtPesoIdeal {
            get {
                return ResourceManager.GetString("txtPesoIdeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano.
        /// </summary>
        public static string txtPlano {
            get {
                return ResourceManager.GetString("txtPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pressão Alta.
        /// </summary>
        public static string txtPressaoAlta {
            get {
                return ResourceManager.GetString("txtPressaoAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Problema Cardíaco.
        /// </summary>
        public static string txtProbCardiaco {
            get {
                return ResourceManager.GetString("txtProbCardiaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Problema Respiratório.
        /// </summary>
        public static string txtProbRespiratorio {
            get {
                return ResourceManager.GetString("txtProbRespiratorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quadril.
        /// </summary>
        public static string txtQuadril {
            get {
                return ResourceManager.GetString("txtQuadril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remédio uso continuo.
        /// </summary>
        public static string txtRemedio {
            get {
                return ResourceManager.GetString("txtRemedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Re-senha.
        /// </summary>
        public static string txtReSenha {
            get {
                return ResourceManager.GetString("txtReSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restrições.
        /// </summary>
        public static string txtRestricoes {
            get {
                return ResourceManager.GetString("txtRestricoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saída.
        /// </summary>
        public static string txtSaida {
            get {
                return ResourceManager.GetString("txtSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        public static string txtSalvar {
            get {
                return ResourceManager.GetString("txtSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Semestral.
        /// </summary>
        public static string txtSemestral {
            get {
                return ResourceManager.GetString("txtSemestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string txtSenha {
            get {
                return ResourceManager.GetString("txtSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string txtSenhah1 {
            get {
                return ResourceManager.GetString("txtSenhah1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        public static string txtTelefone {
            get {
                return ResourceManager.GetString("txtTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tórax.
        /// </summary>
        public static string txtTorax {
            get {
                return ResourceManager.GetString("txtTorax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Treinos.
        /// </summary>
        public static string txtTreinos {
            get {
                return ResourceManager.GetString("txtTreinos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Trimestral.
        /// </summary>
        public static string txtTrimestral {
            get {
                return ResourceManager.GetString("txtTrimestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UF.
        /// </summary>
        public static string txtUf {
            get {
                return ResourceManager.GetString("txtUf", resourceCulture);
            }
        }
    }
}
